### ISSUE TITLE
add version which uses HoTT 

### ISSUE THREAD

**Issue by fpvandoorn** [leanprover/lean.js#2]
I want to write an article about Lean for the HoTT blog in August, and it would be nice if I can then point to a on-line version of Lean which uses the HoTT instantiation of the kernel and the HoTT library.

It can wait until after CADE, because I think you are busy enough until then, but it would be nice if it would be added soon after that.

**Comment by fpvandoorn** [comment]
I'm planning to write the blog post in a couple of days, so it would be nice if you could implement it by then.

**Comment by soonhokong** [comment]
Hi @fpvandoorn, I'm in Germany now. I'll come back to Pittsburgh during the weekend and try something on my VM.

**Comment by fpvandoorn** [comment]
Ok. It can wait until after the weekend. Have a good time in Germany!

**Comment by fpvandoorn** [comment]
Sorry to push you, but I finished the blog post, so it would be really nice if you can add this soon.

**Comment by soonhokong** [comment]
I see. I'll check this evening.

**Comment by fpvandoorn** [comment]
It's been two months... Could you try to spend some time on it soon? If there is anything I can do to help, please let me know.

I just checked, and there were some theorems which needed to be definitions for the HoTT library to compile with the `--to_axiom` flag. On my `master` and `typeclass` branch I fixed this:
https://github.com/fpvandoorn/lean/tree/master
https://github.com/fpvandoorn/lean/tree/typeclass

**Comment by soonhokong** [comment]
sorry for the delay.. I'll check it soon.

**Comment by fpvandoorn** [comment]
Any progress?

I'm worried that the HoTT-library is too big for a web version, because so many statements are `definitions` instead of `theorems`. If that is indeed the case, then maybe you can not load the contents of the `algebra/category` folder? If it's still too big then, I'll think about what we can skip after that.

**Comment by fpvandoorn** [comment]
@soonhokong: I'm going to rewrite my blog post so that it doesn't assume that there is a online version of HoTT-Lean, so this issue is lower priority now (you can close it if you want).

**Comment by soonhokong** [comment]
I'm so sorry... I'll keep it open and give it a shot when I get some time for this..

**Comment by wizardbc** [comment]
I think I've created hlean.js (java script version of HoTT-Lean) by a simple trick.

But, I'm not familiar with git and neither a member of this project.
So I just share some idea and ask you to do some test.

And I am a newbie in both HoTT and Lean. I'm trying to study :)
Anyway, I don't know is it works good enough.

I have my own test server (https://wizard.undo.it/lean/).
But, it is unstable and untrusted.
So I think you want build your own hlean.js file.

What I did is simple, just put the hott directory of lean, into the library directory of lean_js/shell

**Comment by wizardbc** [comment]
I've build hlean.js (javascript for online version of HoTT-Lean) by a simple trick.
Just replace library.tar.gz by hott.tar.gz file in Makefile.

Because I'm not familiar with git and neither an expert in HoTT-Lean,
I ask you to do some test, is it works good enough.

I have my own test server (https://wizard.undo.it/lean).
This server allows only SSL connection (https, not http).
But it is unstable and untrusted, your browser will warn you this.
So I think you want to make your own hlean.js and test it with lean/tutorial.

I will describe what I did:

* Modify Makefile:
```Makefile
all: lean.js
        echo "done"

lean.js: libs/libgmp.so libs/libmpfr.so libs/liblua.so build/lean/source/lean-master/shell/lean build/lean/source/lean-master/hott.tar.gz
        python build_all.py lean_js
        rm -rf build/lean_js/source/lean-master/shell/library
        cd build/lean_js/source/lean-master/shell && tar xvfz ../../../../lean/source/lean-master/hott.tar.gz && mv hott library
        rm -rf build/lean_js/source/lean-master/shell/lean.*
        emmake make -C build/lean_js/source/lean-master/ || emmake make -C build/lean_js/source/lean-master/ || emmake make -C build/lean_js/source/lean-master/

build/lean/source/lean-master/shell/lean:
        python build_all.py lean

build/lean/source/lean-master/hott.tar.gz: build/lean/source/lean-master/shell/lean
        cp .project build/lean/source/lean-master/hott
        cd build/lean/source/lean-master/hott && find . -name "*.olean" -delete
        # removed -X option. There is an error with -X option.
        cd build/lean/source/lean-master/hott && ../bin/linja clean && ../bin/linja
        cd build/lean/source/lean-master && tar cvfz hott.tar.gz `find hott -name "*.olean"`

libs/libgmp.so:
       python build_all.py gmp

libs/libmpfr.so:
        python build_all.py mpfr

libs/liblua.so:
        python build_all.py lua

#push:
#       git checkout gh-pages
#       git reset --hard origin/gh-pages~
#       cp build/lean_js/source/lean-master/shell/lean.js lean.js
#       git add lean.js
#       git commit -m "Update `date -R`"
#       git push --force origin gh-pages:gh-pages
#       git checkout master

clean:
        rm -rf build libs includes

.PHONY: all gmp mpfr lua lean lean.js clean
```

If `python build_all.py lean` does not work near 83%, and the memory runs out, 
edit 'components/lean/config.py' and 'components/lean_js/config.py'.
Replace `emmake make -j` by `emmake make -j7` (the integer after -j can be changed depending on your machine).

* Anyway, it will stop at `python build_all.py lean_js` because of some error about `O_CREAT`.

Just put `#include <fcntl.h> ` in `build/lean_js/source/lean-master/src/util/file_lock.cpp`.

Comment out `#        python build_all.py lean_js` in Makefile and do
```shell
$ emmake make -C build/lean_js/source/lean-master/
$ make
```

* Now you can find `lean.js` file in `build/lean_js/source/lean-master/shell` directory. It will be about 22MB.

* Copy this to somewhere public (I changed the filename to `hlean.js` and place in `lean/tutorial/lean.js/hlean.js`) and modify `leanprover/tutorial/js/main_live.js`:
find `\.lean` in main_live.js file, then replace
```javascript
    var default_filename = "input.lean";
```
to
```javascript
    var default_filename = "input.hlean";
```

* Also in `lean/tutorial/js/main_live.js`:
```javascript
       myModule.import_module("standard");
```
to
```javascript
       myModule.import_module("core");
```

* Modify `leanprover/tutorial/index.html`:
```html
    <script src="//leanprover.github.io/lean.js/lean.js" type="text/javascript" charset="utf-8"></script>
```
to
```html
    <script src="lean.js/hlean.js" type="text/javascript" charset="utf-8"></script>
```

* Now start the tutorial at `leanprover/tutorial/`:
```shell
$ python -m SimpleHTTPServer
```



That's what I've done.
I hope this will help to make an online version of HoTT-Lean officially.

Thank you.

**Comment by soonhokong** [comment]
@wizardbc, thanks for working on this!!

@fpvandoorn, one of my concern was that we throw away the contents of proofs after type-checking them to reduce the size of `.js` file. Floris, is it a big problem in HOTT? Also, could you try your `cpp.hlean` at https://wizard.undo.it/lean/index.html?live ? It gives me errors. For example

```lean
line 41, column 20: error: tactic failed
A : Type,
P : one_step_tr → Type,
Pt : Π (a : A), P (tr a),
Pe : Π (a a' : A), Pt a =[tr_eq a a'] Pt a',
x : one_step_tr,
a a' : A,
H : one_step_tr.R a a'
⊢ Pt a =[eq_of_rel one_step_tr.R H] Pt a'
```

and I'm wondering why we have this...

**Comment by fpvandoorn** [comment]
@wizardbc: Thanks for looking into this!

@soonhokong: We can throw away the contents of all theorems for the HoTT library. I've kept the convention that everything which we need to unfold is a `definition`. However, I made a couple of mistakes when porting, so the library currently fails to compile with the `to_axiom` flag. I will make a pull request with a fix. 

@leodemoura: could we add a test to the test suite which compiles the HoTT library with the `--to_axiom` option enabled?

The error messages when compiling my `cpp.hlean` file probably all come because Lean still thinks it's using the standard version. The first error message is because the `cases` tactic fails, which (I believe) works differently in the standard library and the HoTT library, and the second error message is because the computation rules for the HIT-recursors are not loaded properly. Also, the bottom universe is still impredicative, for example the code `check lift.{0 3} nat -> nat` returns `Type.{0}` instead of `Type.{3}`. These are the options used for the HoTT library: https://github.com/leanprover/lean/blob/master/src/library/hott_kernel.cpp

**Comment by leodemoura** [comment]
> @leodemoura: could we add a test to the test suite which compiles the HoTT library with the --to_axiom option enabled?

Yes, we can.

**Comment by wizardbc** [comment]
I've made some progress in this issue.

* Change Makefile, major cahnges are as follows:
```Makefile
all: hlean.js
        echo "done"

hlean.js: libs/libgmp.so libs/libmpfr.so libs/liblua.so build/lean/source/lean-master/shell/lean build/lean/source/lean-master/hott.tar.gz
        python build_all.py lean_js
        rm -rf build/lean_js/source/lean-master/shell/hott
        cd build/lean_js/source/lean-master/shell && tar xvfz ../../../../lean/source/lean-master/hott.tar.gz
        rm -rf build/lean_js/source/lean-master/shell/lean.*
        emmake make -C build/lean_js/source/lean-master/ || emmake make -C build/lean_js/source/lean-master/ || emmake make -C build/lean_js/source/lean-master/

build/lean/source/lean-master/hott.tar.gz: build/lean/source/lean-master/shell/lean
        cp .project build/lean/source/lean-master/hott
        cd build/lean/source/lean-master/hott && find . -name "*.olean" -delete
        cd build/lean/source/lean-master/hott && ../bin/linja clean && ../bin/linja -X
        cd build/lean/source/lean-master && tar cvfz hott.tar.gz `find hott -name "*.olean"`
```

* Edit .project file:
```
+ *.lean
+ *.hlean
- flycheck*.lean
- flycheck*.hlean
- .#*.lean
- .#*.lean
- theories/
```

* Do `make`.

* It will stop with error, because `O_CREAT` is undefined. Insert `#include <fcntl.h>` in 'build/lean_js/source/lean-master/src/util/file_lock.cpp'.

* Comment out `#python build_all.py lean_js` in the Makefile and do `make` again.

* Now we are trying to make Lean think it is in HoTT mode by default.

* In 'build/lean_js/source/lean-master/src/shell/lean.cpp`, line 286,
```cpp
    //input_kind default_k = input_kind::Unspecified;
    input_kind default_k = input_kind::HLean;
```

* In 'build/lean_js/source/lean-master/src/shell/emscripten.cpp`, line 11,
```cpp
//#include "library/standard_kernel.h"
#include "library/hott_kernel.h"
```
,line 33
```cpp
        //env(mk_environment(trust_lvl)), ios(opts, lean::mk_pretty_formatter_factory()),
        env(mk_hott_environment(trust_lvl)), ios(opts, lean::mk_pretty_formatter_factory()),
```

* in 'build/lean_js/source/lean-master/src/util/init_module.cpp', line 28,
```cpp
    //initialize_lean_path();
    initialize_lean_path(true);
```

* In 'build/lean_js/source/lean-master/src/util/lean_path.cpp', line 121,
```cpp
#if defined(LEAN_EMSCRIPTEN)
    //*g_lean_path = "/library";
    if (use_hott)
        *g_lean_path = "/hott";
    else
        *g_lean_path = "/library";
    g_lean_path_vector->push_back(*g_lean_path);
#else
```

* In `build/lean_js/source/lean-master/shell/CMakeFiles/lean.js.dir/link.txt` add `--embed-file hott`.

* Finally, do `make`.

* In 'run_lean_js.sh', line 46, remove `Module.lean_import_module('standard');` and add below:
```shell-script
Module.lean_import_module('core');
```

* Let's do some test.
```shell-script
$ ./run_lean_js.sh build/lean_js/source/lean-master/shell/lean.js some.hlean
```

* I've tried @fpvandoorn 's `cpp.hlean` and it looks like working. But, I'm not an expert in this area, pleas check it. 

* You can test this lean.js at https://wizard.undo.it/lean/hlean.html?live
But, this server is unstable and untrusted.


Thank you.

**Comment by fpvandoorn** [comment]
I tried a couple of other files, and those also all worked. That is awesome! Thanks for working on this.

**Comment by soonhokong** [comment]
@wizardbc, great! I'll merge this into the main repo.

**Comment by soonhokong** [comment]
@wizardbc, I was able to generate a new version of `lean.js` which can handle both of `.lean` and `.hlean`. Its size is about 24MB which is about 10MB larger than the current version (which can only handle `.lean` file).

https://github.com/leanprover/lean.js/commit/61ee8244315afceeed846e865b1b4f13d6b7012d and https://github.com/soonhokong/lean/commit/8612bdae246296da803849b39900827cce3166ea are the changes that I made to merge the two versions.

I'm still thinking about how to update the web interface to enable both of kernels. I'll write another comment about that later. Thanks for the contribution!

**Comment by fpvandoorn** [comment]
So do you need to download both the standard library and the HoTT library to work in Lean in your browser? I would also be happy with two separate pages, one which only works for `.lean` files, and one which only works for `.hlean` files. But if I understand your comment correctly there is now one version which can handle both types of files. And then there would be an option whether you're using the standard version or the HoTT version? That would also be great (especially if there is a new url which starts `lean.js` using HoTT by default).

**Comment by soonhokong** [comment]
@fpvandoorn, please try the following examples:
 - https://leanprover.github.io/tutorial/?live&hott
 - https://leanprover.github.io/tutorial/?live&url=http://www.contrib.andrew.cmu.edu/~fpv/files/cpp.hlean
 - https://leanprover.github.io/tutorial/?live&url=https://github.com/EgbertRijke/sequential_colimits/blob/master/move_to_lib.hlean

**Comment by fpvandoorn** [comment]
They all work! That's great! Thank you and @wizardbc for implementing this!

**Comment by fpvandoorn** [comment]
I now also linked to it in my blog post: http://homotopytypetheory.org/2015/12/02/the-proof-assistant-lean/
